version: "3.9"

services:
  gmeet-clone:
    build: .
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.gmeetclone-secure.entrypoints=websecure"
      - "traefik.http.routers.gmeetclone-secure.rule=Host(`gmeetclone.x-axis.me`)"
      - "traefik.http.routers.gmeetclone-secure.service=gmeetclone-service"
      - "traefik.http.services.gmeetclone-service.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
